apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-mongodb-0
  namespace: nbacha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
