apiVersion: v1
kind: Service
metadata:
  name: mongodb  # Name of the service
spec:
  type: ClusterIP  # Service type, internal only
  selector:
    app: mongodb  # Match the 'mongodb' pods
  ports:
  - protocol: TCP
    port: 27017       # Port to access the service
    targetPort: 27017 # Port where the MongoDB container listens
