apiVersion: v1
kind: Service
metadata:
  name: webdb  # Name of the service
spec:
  type: ClusterIP  # Service type, internal only
  selector:
    app: webdb  # Match the 'webdb' pods
  ports:
  - protocol: TCP
    port: 5000         # Port to access the service
    targetPort: 5000   # Port where the container listens
