apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  labels:
    app: webdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: bachboucha/challenge4-flask_with_db
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
