apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: nbacha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "400m"
            memory: "400Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: nbacha
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: nbacha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: bachboucha/challenge4-flask_with_db
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://admin:password@mongodb-service.nbacha.svc.cluster.local:27017/" # MongoDB URL
        - name: MONGO_DB
          value: "MANGO_DB"  
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: nbacha
spec:
  selector:
    app: webdb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
