webdb:
  image: bachboucha/challenge13-webdb:v1.2
  replicas: 3
  service:
    port: 5000
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"
  environment:
    MONGODB_HOST: "mongodb-0.mongodb.nbacha.svc.cluster.local"  # Updated for headless service
    MONGODB_PORT: "27017"

webnodb:
  image: bachboucha/challenge13-webnodb:v1.2
  replicas: 2
  service:
    port: 5000
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

mongodb:
  image: mongo:latest
  replicas: 1
  service:
    port: 27017
  volume:
    size: "0.1Gi"
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

ingress:
  hostnames:
    - webnodb.nbacha.net4255.luxbulb.org
    - webdb.nbacha.net4255.luxbulb.org
