apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: nbacha
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017