apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: nbacha
  labels:
    app: mongodb
spec:
  clusterIP: None  # Headless service
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.port }}
