apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: nbacha
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data-mongodb-0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: nbacha
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.port }}
  selector:
    app: mongodb
