apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: nbacha
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000 # Match the containerPort in the Deployment
  type: ClusterIP
