apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
        resources:
          requests:
            memory: {{ .Values.mongodb.resources.requests.memory }}
            cpu: {{ .Values.mongodb.resources.requests.cpu }}
          limits:
            memory: {{ .Values.mongodb.resources.limits.memory }}
            cpu: {{ .Values.mongodb.resources.limits.cpu }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.port }}
  type: ClusterIP
