apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: nbacha
spec:
  serviceName: mongodb
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          command:
            - "mongod"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: {{ .Values.mongodb.service.port }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mongodb.volume.size }}
